#include-once

Func _iForm()
    Local Const $this = _AutoItObject_Class()

	$this.Create()

	$this.AddMethod("Child"          , "GUIObjects_Form_Child"          )
	$this.AddMethod("Show"           , "GUIObjects_Form_Show"           )
	$this.AddMethod("Hide"           , "GUIObjects_Form_Hide"           )
	$this.AddMethod("Minimize"       , "GUIObjects_Form_Minimize"       )
	$this.AddMethod("Maximize"       , "GUIObjects_Form_Maximize"       )
	$this.AddMethod("Restore"        , "GUIObjects_Form_Restore"        )
	$this.AddMethod("Disable"        , "GUIObjects_Form_Disable"        )
	$this.AddMethod("Enable"         , "GUIObjects_Form_Enable"         )
	$this.AddMethod("Lock"           , "GUIObjects_Form_Lock"           )
	$this.AddMethod("Unlock"         , "GUIObjects_Form_Unlock"         )
	$this.AddMethod("ShowDefault"    , "GUIObjects_Form_ShowDefault"    )
	$this.AddMethod("ShowMaximized"  , "GUIObjects_Form_ShowMaximized"  )
	$this.AddMethod("ShowMinimized"  , "GUIObjects_Form_ShowMinimized"  )
	$this.AddMethod("ShowMinNoActive", "GUIObjects_Form_ShowMinNoActive")
	$this.AddMethod("ShowNA"         , "GUIObjects_Form_ShowNA"         )
	$this.AddMethod("ShowNormal"     , "GUIObjects_Form_ShowNormal"     )
	$this.AddMethod("Delete"         , "GUIObjects_Form_Delete"         )
	$this.AddMethod("SetDefBkColor"  , "GUIObjects_Form_SetDefBkColor"  )
	$this.AddMethod("SetDefColor"    , "GUIObjects_Form_SetDefColor"    )
	$this.AddMethod("SetBkColor"     , "GUIObjects_Form_SetBkColor"     )
	$this.AddMethod("SetCursor"      , "GUIObjects_Form_SetCursor"      )
	$this.AddMethod("SetFont"        , "GUIObjects_Form_SetFont"        )
	$this.AddMethod("GetStyle"       , "GUIObjects_Form_GetStyle"       )
	$this.AddMethod("GetExStyle"     , "GUIObjects_Form_GetExStyle"     )
	$this.AddMethod("SetStyle"       , "GUIObjects_Form_SetStyle"       )
	$this.AddMethod("SetExStyle"     , "GUIObjects_Form_SetExStyle"     )
	$this.AddMethod("SetHelp"        , "GUIObjects_Form_SetHelp"        )
	$this.AddMethod("SetOnEvent"     , "GUIObjects_Form_SetOnEvent"     )
	$this.AddMethod("RegisterMsg"    , "GUIObjects_Form_RegisterMsg"    )
	$this.AddMethod("SetAccelerators", "GUIObjects_Form_SetAccelerators")
	$this.AddMethod("GetCursorInfo"  , "GUIObjects_Form_GetCursorInfo"  )
	$this.AddMethod("", "GUIObjects_Form_")

	$this.AddMethod("AVI"     , "GUIObjects_AVI"     )
	$this.AddMethod("Button"  , "GUIObjects_Button"  )
	$this.AddMethod("Checkbox", "GUIObjects_Checkbox")
	$this.AddMethod("Combo"   , "GUIObjects_Combo"   )
	$this.AddMethod("Date"    , "GUIObjects_Date"    )
	$this.AddMethod("Edit"    , "GUIObjects_Edit"    )
	$this.AddMethod("Label"   , "GUIObjects_Label"   )
	$this.AddMethod("Listbox" , "GUIObjects_Listbox" )
	$this.AddMethod("Listview", "GUIObjects_Listview")
	$this.AddMethod("Menu"    , "GUIObjects_Menu"    )
	$this.AddMethod("MonthCal", "GUIObjects_MonthCal")
	$this.AddMethod("Progress", "GUIObjects_Progress")
	$this.AddMethod("Slider"  , "GUIObjects_Slider"  )
	$this.AddMethod("Tab"     , "GUIObjects_Tab"     )
	$this.AddMethod("TreeView", "GUIObjects_TreeView")
	$this.AddMethod("UpDown"  , "GUIObjects_UpDown"  )

	$this.AddProperty("Handle" , $ELSCOPE_PUBLIC)
	$this.AddProperty("Title"  , $ELSCOPE_PUBLIC)
	$this.AddProperty("Width"  , $ELSCOPE_PUBLIC)
	$this.AddProperty("Height" , $ELSCOPE_PUBLIC)
	$this.AddProperty("Left"   , $ELSCOPE_PUBLIC)
	$this.AddProperty("Top"    , $ELSCOPE_PUBLIC)
	$this.AddProperty("Style"  , $ELSCOPE_PUBLIC)
	$this.AddProperty("ExStyle", $ELSCOPE_PUBLIC)
	$this.AddProperty("Locked" , $ELSCOPE_PUBLIC, False)
	$this.AddProperty("", $ELSCOPE_PUBLIC)

    Return $this.Object
EndFunc
